#Requires -Version 5.1
<#
.SYNOPSIS
    AtCoder ABC コンテスト用フォルダを自動生成するスクリプト

.DESCRIPTION
    指定された回数のAtCoder Beginner Contest (ABC) 用のフォルダを作成し、
    テンプレートファイルをコピーして、コンテスト情報付きのREADME.mdを生成します。

.PARAMETER ContestNumber
    作成するコンテストの回数（必須）

.PARAMETER Force
    既存のフォルダがある場合に上書きします

.PARAMETER Open
    作成後にフォルダを開きます

.PARAMETER Language
    使用言語を指定します（cpp, python, both）。デフォルトはboth

.PARAMETER Date
    コンテスト開催日を指定します（YYYY-MM-DD形式）

.EXAMPLE
    .\create_abc.ps1 372
    ABC372フォルダを作成

.EXAMPLE
    .\create_abc.ps1 372 -Force -Open -Date "2025-01-01"
    ABC372フォルダを強制作成し、開催日を設定してフォルダを開く

.EXAMPLE
    .\create_abc.ps1 372 -Language cpp
    C++テンプレートのみでABC372フォルダを作成
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true, Position=0)]
    [ValidateRange(1, 999)]
    [int]$ContestNumber,

    [Parameter()]
    [switch]$Force,

    [Parameter()]
    [switch]$Open,

    [Parameter()]
    [ValidateSet("cpp", "python", "both")]
    [string]$Language = "both",

    [Parameter()]
    [ValidatePattern('^\d{4}-\d{2}-\d{2}$')]
    [string]$Date,

    [Parameter()]
    [switch]$VSCode,

    [Parameter()]
    [switch]$CreateTestFiles
)

# エラー処理の設定
$ErrorActionPreference = 'Stop'

# スクリプト情報
$ScriptVersion = "2.0.0"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$TemplateDir = Join-Path $ScriptDir "template"
$NewDirName = "ABC$ContestNumber"
$NewDirPath = Join-Path $ScriptDir $NewDirName

Write-Host "🚀 AtCoder ABC フォルダ生成ツール v$ScriptVersion" -ForegroundColor Cyan
Write-Host "=" * 50 -ForegroundColor Gray

# バリデーション
function Test-Prerequisites {
    # テンプレートディレクトリの存在確認
    if (!(Test-Path $TemplateDir)) {
        throw "テンプレートディレクトリ '$TemplateDir' が見つかりません。"
    }

    # 必要なテンプレートファイルの確認
    $requiredFiles = @()
    if ($Language -eq "cpp" -or $Language -eq "both") {
        $requiredFiles += "main.cpp"
    }
    if ($Language -eq "python" -or $Language -eq "both") {
        $requiredFiles += "main.py"
    }

    foreach ($file in $requiredFiles) {
        $filePath = Join-Path $TemplateDir $file
        if (!(Test-Path $filePath)) {
            throw "必要なテンプレートファイル '$file' が見つかりません。"
        }
    }

    # 既存ディレクトリのチェック
    if (Test-Path $NewDirPath) {
        if ($Force) {
            Write-Warning "既存のディレクトリ '$NewDirName' を削除します..."
            Remove-Item -Path $NewDirPath -Recurse -Force
        } else {
            throw "ディレクトリ '$NewDirName' は既に存在します。-Force オプションを使用して上書きしてください。"
        }
    }

# README.md生成関数
function New-ReadmeContent {
    param([int]$Number, [string]$ContestDate)
    
    $dateString = if ($ContestDate) { $ContestDate } else { "未定" }
    
    return @"
# AtCoder Beginner Contest $Number

## 📊 コンテスト情報
- **コンテストURL**: [https://atcoder.jp/contests/abc$Number/tasks](https://atcoder.jp/contests/abc$Number/tasks)
- **開催日**: $dateString
- **結果**: 未参加
- **順位**: -
- **レーティング変化**: -

---

## 📋 問題一覧

### 🅰️ A問題
- **問題URL**: [https://atcoder.jp/contests/abc$Number/tasks/abc$($Number)_a](https://atcoder.jp/contests/abc$Number/tasks/abc$($Number)_a)
- **難易度**: -
- **結果**: 未提出
- **実行時間**: -
- **メモリ**: -
- **提出時間**: -

#### 💡 解法メモ


#### 🔧 何を使って解けた？


#### ❌ 何がダメだった？


#### 🔄 別の方法は？


---

### 🅱️ B問題
- **問題URL**: [https://atcoder.jp/contests/abc$Number/tasks/abc$($Number)_b](https://atcoder.jp/contests/abc$Number/tasks/abc$($Number)_b)
- **難易度**: -
- **結果**: 未提出
- **実行時間**: -
- **メモリ**: -
- **提出時間**: -

#### 💡 解法メモ


#### 🔧 何を使って解けた？


#### ❌ 何がダメだった？


#### 🔄 別の方法は？


---

### 🅲 C問題
- **問題URL**: [https://atcoder.jp/contests/abc$Number/tasks/abc$($Number)_c](https://atcoder.jp/contests/abc$Number/tasks/abc$($Number)_c)
- **難易度**: -
- **結果**: 未提出
- **実行時間**: -
- **メモリ**: -
- **提出時間**: -

#### 💡 解法メモ


#### 🔧 何を使って解けた？


#### ❌何がダメだった？


#### 🔄 別の方法は？


---

### 🅳 D問題
- **問題URL**: [https://atcoder.jp/contests/abc$Number/tasks/abc$($Number)_d](https://atcoder.jp/contests/abc$Number/tasks/abc$($Number)_d)
- **難易度**: -
- **結果**: 未提出
- **実行時間**: -
- **メモリ**: -
- **提出時間**: -

#### 💡 解法メモ


#### 🔧 何を使って解けた？


#### ❌ 何がダメだった？


#### 🔄 別の方法は？


---

## 📈 全体の振り返り

### ✅ 良かった点


### 📉 改善点


### 🎯 次回に向けて


### 📚 学んだこと


---

## 🛠️ 技術情報

### 使用言語・ライブラリ
$(if ($Language -eq "cpp" -or $Language -eq "both") { "- C++ (AtCoder Library)" })
$(if ($Language -eq "python" -or $Language -eq "both") { "- Python 3" })

### 開発環境
- **エディタ**: Visual Studio Code
- **OS**: Windows 10/11
- **作成日**: $(Get-Date -Format 'yyyy年MM月dd日')

### ファイル構成
```
ABC$Number/
$(if ($Language -eq "cpp" -or $Language -eq "both") { "├── main.cpp      # C++テンプレートファイル" })
$(if ($Language -eq "python" -or $Language -eq "both") { "├── main.py       # Pythonテンプレートファイル" })
└── README.md     # このファイル
```

---

**Generated by**: AtCoder ABC フォルダ生成ツール v$ScriptVersion  
**Creation Date**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
"@
}

# メイン処理
try {
    # 前提条件チェック
    Test-Prerequisites

    # ディレクトリ作成
    Write-Host "📁 ディレクトリ '$NewDirName' を作成中..." -ForegroundColor Yellow
    New-Item -Path $NewDirPath -ItemType Directory -Force | Out-Null
    Write-Host "   ✅ ディレクトリを作成しました" -ForegroundColor Green

    # テンプレートファイルのコピー
    Write-Host "📄 テンプレートファイルをコピー中..." -ForegroundColor Yellow
    $copiedFiles = @()

    if ($Language -eq "cpp" -or $Language -eq "both") {
        $cppSource = Join-Path $TemplateDir "main.cpp"
        $cppDest = Join-Path $NewDirPath "main.cpp"
        Copy-Item -Path $cppSource -Destination $cppDest
        $copiedFiles += "main.cpp"
        Write-Host "   ✅ main.cpp をコピーしました" -ForegroundColor Green
    }

    if ($Language -eq "python" -or $Language -eq "both") {
        $pySource = Join-Path $TemplateDir "main.py"
        $pyDest = Join-Path $NewDirPath "main.py"
        Copy-Item -Path $pySource -Destination $pyDest
        $copiedFiles += "main.py"
        Write-Host "   ✅ main.py をコピーしました" -ForegroundColor Green
    }

    # README.md生成
    Write-Host "📝 README.md を生成中..." -ForegroundColor Yellow
    $readmeContent = New-ReadmeContent -Number $ContestNumber -ContestDate $Date
    $readmePath = Join-Path $NewDirPath "README.md"
    $readmeContent | Out-File -FilePath $readmePath -Encoding UTF8
    Write-Host "   ✅ README.md を生成しました" -ForegroundColor Green

    # 成功メッセージ
    Write-Host "`n" + ("=" * 50) -ForegroundColor Gray
    Write-Host "🎉 ABC$ContestNumber のフォルダ作成が完了しました！" -ForegroundColor Green
    Write-Host "� 作成場所: $NewDirPath" -ForegroundColor Cyan
    Write-Host "📋 作成されたファイル:" -ForegroundColor Cyan
    foreach ($file in ($copiedFiles + "README.md")) {
        Write-Host "   - $file" -ForegroundColor White
    }

    # フォルダを開く
    if ($Open) {
        Write-Host "📁 フォルダを開いています..." -ForegroundColor Yellow
        Start-Process explorer.exe -ArgumentList $NewDirPath
    }

    Write-Host "`n🚀 コンテスト頑張ってください！" -ForegroundColor Magenta

} catch {
    Write-Host "`n❌ エラーが発生しました: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}