#Requires -Version 5.1
<#
.SYNOPSIS
    AtCoder ABC コンテスト用フォルダを自動生成するスクリプト

.PARAMETER ContestNumber
    作成するコンテストの回数（必須）

.PARAMETER Force
    既存のフォルダがある場合に上書きします

.PARAMETER Open
    作成後にフォルダを開きます

.PARAMETER Language
    使用言語を指定します（cpp, python, both）。デフォルトはboth

.PARAMETER Date
    コンテスト開催日を指定します（YYYY-MM-DD形式）

.PARAMETER VSCode
    作成後にVS Codeで開きます

.PARAMETER CreateTestFiles
    テスト用入力ファイルを作成します
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true, Position=0)]
    [ValidateRange(1, 999)]
    [int]$ContestNumber,

    [Parameter()]
    [switch]$Force,

    [Parameter()]
    [switch]$Open,

    [Parameter()]
    [ValidateSet("cpp", "python", "both")]
    [string]$Language = "both",

    [Parameter()]
    [ValidatePattern('^\d{4}-\d{2}-\d{2}$')]
    [string]$Date,

    [Parameter()]
    [switch]$VSCode,

    [Parameter()]
    [switch]$CreateTestFiles,

    [Parameter()]
    [switch]$ContestMode
)

# エラー処理の設定
$ErrorActionPreference = 'Stop'

# スクリプト情報
$ScriptVersion = "2.0.0"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$TemplateDir = Join-Path $ScriptDir "template"
$NewDirName = "ABC$ContestNumber"
$NewDirPath = Join-Path $ScriptDir $NewDirName

Write-Host "🚀 AtCoder ABC フォルダ生成ツール v$ScriptVersion" -ForegroundColor Cyan
Write-Host ("=" * 50) -ForegroundColor Gray

try {
    # 前提条件チェック
    if (!(Test-Path $TemplateDir)) {
        throw "テンプレートディレクトリ '$TemplateDir' が見つかりません。"
    }

    # 既存ディレクトリのチェック
    if (Test-Path $NewDirPath) {
        if ($Force) {
            Write-Warning "既存のディレクトリ '$NewDirName' を削除します..."
            Remove-Item -Path $NewDirPath -Recurse -Force
        } else {
            throw "ディレクトリ '$NewDirName' は既に存在します。-Force オプションを使用して上書きしてください。"
        }
    }

    # ディレクトリ作成
    Write-Host "📁 ディレクトリ '$NewDirName' を作成中..." -ForegroundColor Yellow
    New-Item -Path $NewDirPath -ItemType Directory -Force | Out-Null
    Write-Host "   ✅ ディレクトリを作成しました" -ForegroundColor Green

    # テンプレートファイルのコピー
    Write-Host "📄 テンプレートファイルをコピー中..." -ForegroundColor Yellow
    $copiedFiles = @()

    if ($Language -eq "cpp" -or $Language -eq "both") {
        $cppSource = Join-Path $TemplateDir "main.cpp"
        if (Test-Path $cppSource) {
            $cppDest = Join-Path $NewDirPath "main.cpp"
            Copy-Item -Path $cppSource -Destination $cppDest
            $copiedFiles += "main.cpp"
            Write-Host "   ✅ main.cpp をコピーしました" -ForegroundColor Green
        }
    }

    if ($Language -eq "python" -or $Language -eq "both") {
        $pySource = Join-Path $TemplateDir "main.py"
        if (Test-Path $pySource) {
            $pyDest = Join-Path $NewDirPath "main.py"
            Copy-Item -Path $pySource -Destination $pyDest
            $copiedFiles += "main.py"
            Write-Host "   ✅ main.py をコピーしました" -ForegroundColor Green
        }
    }

    # README.md生成
    Write-Host "📝 README.md を生成中..." -ForegroundColor Yellow
    $dateString = if ($Date) { $Date } else { "未定" }
    
    $readmeContent = @"
# AtCoder Beginner Contest $ContestNumber

## 📊 コンテスト情報
- **コンテストURL**: [https://atcoder.jp/contests/abc$ContestNumber/tasks](https://atcoder.jp/contests/abc$ContestNumber/tasks)
- **開催日**: $dateString
- **結果**: 未参加
- **順位**: -
- **レーティング変化**: -

---

## 📋 問題一覧

### 🅰️ A問題
- **問題URL**: [https://atcoder.jp/contests/abc$ContestNumber/tasks/abc$($ContestNumber)_a](https://atcoder.jp/contests/abc$ContestNumber/tasks/abc$($ContestNumber)_a)
- **難易度**: -
- **結果**: 未提出
- **実行時間**: -
- **メモリ**: -

#### 💡 解法メモ


#### 🔧 何を使って解けた？


#### ❌ 何がダメだった？


#### 🔄 別の方法は？


---

### 🅱️ B問題
- **問題URL**: [https://atcoder.jp/contests/abc$ContestNumber/tasks/abc$($ContestNumber)_b](https://atcoder.jp/contests/abc$ContestNumber/tasks/abc$($ContestNumber)_b)
- **難易度**: -
- **結果**: 未提出

#### 💡 解法メモ


---

### 🅲 C問題
- **問題URL**: [https://atcoder.jp/contests/abc$ContestNumber/tasks/abc$($ContestNumber)_c](https://atcoder.jp/contests/abc$ContestNumber/tasks/abc$($ContestNumber)_c)
- **難易度**: -
- **結果**: 未提出

#### 💡 解法メモ


---

### 🅳 D問題
- **問題URL**: [https://atcoder.jp/contests/abc$ContestNumber/tasks/abc$($ContestNumber)_d](https://atcoder.jp/contests/abc$ContestNumber/tasks/abc$($ContestNumber)_d)
- **難易度**: -
- **結果**: 未提出

#### 💡 解法メモ


---

## 📈 全体の振り返り

### ✅ 良かった点


### 📉 改善点


### 🎯 次回に向けて


---

**Generated by**: AtCoder ABC フォルダ生成ツール v$ScriptVersion  
**Creation Date**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
"@
    
    $readmePath = Join-Path $NewDirPath "README.md"
    $readmeContent | Out-File -FilePath $readmePath -Encoding UTF8
    Write-Host "   ✅ README.md を生成しました" -ForegroundColor Green

    # テストファイルの作成
    if ($CreateTestFiles) {
        Write-Host "🧪 テストファイルを作成中..." -ForegroundColor Yellow
        $problems = @("a", "b", "c", "d")
        foreach ($problem in $problems) {
            $inputSource = Join-Path $TemplateDir "input_$problem.txt"
            if (Test-Path $inputSource) {
                $inputDest = Join-Path $NewDirPath "input_$problem.txt"
                Copy-Item -Path $inputSource -Destination $inputDest
                Write-Host "   ✅ input_$problem.txt を作成しました" -ForegroundColor Green
            }
        }
    }

    # コンテスト支援ツールのコピー
    if ($ContestMode) {
        Write-Host "🎯 コンテスト支援ツールを設定中..." -ForegroundColor Yellow
        
        $helperFiles = @("test_runner.ps1", "contest_helper.ps1")
        foreach ($file in $helperFiles) {
            $source = Join-Path $TemplateDir $file
            if (Test-Path $source) {
                $dest = Join-Path $NewDirPath $file
                Copy-Item -Path $source -Destination $dest
                Write-Host "   ✅ $file をコピーしました" -ForegroundColor Green
            }
        }
        
        # クイック実行用バッチファイル作成
        $quickTestBat = @"
@echo off
echo 🧪 クイックテスト実行
echo 使用方法: test.bat [問題] [言語]
echo 例: test.bat a python

if "%~1"=="" goto help
if "%~2"=="" goto help

powershell.exe -ExecutionPolicy Bypass -File "test_runner.ps1" -Problem %1 -Language %2
goto end

:help
echo 問題: a, b, c, d
echo 言語: cpp, python
pause

:end
"@
        $quickTestPath = Join-Path $NewDirPath "test.bat"
        $quickTestBat | Out-File -FilePath $quickTestPath -Encoding ASCII
        Write-Host "   ✅ test.bat を作成しました" -ForegroundColor Green
        
        # コンテスト支援バッチファイル作成
        $contestBat = @"
@echo off
echo 🎯 AtCoder コンテスト支援
echo.
echo 1. 全問題を開く  : contest.bat open $ContestNumber
echo 2. タイマー      : contest.bat timer  
echo 3. 状況確認      : contest.bat status
echo 4. 提出チェック  : contest.bat submit [問題] [言語]
echo 5. ヘルプ        : contest.bat help
echo.

if "%~1"=="open" powershell.exe -ExecutionPolicy Bypass -File "contest_helper.ps1" -Action OpenProblems -ContestNumber %2
if "%~1"=="timer" powershell.exe -ExecutionPolicy Bypass -File "contest_helper.ps1" -Action Timer
if "%~1"=="status" powershell.exe -ExecutionPolicy Bypass -File "contest_helper.ps1" -Action Status
if "%~1"=="submit" powershell.exe -ExecutionPolicy Bypass -File "contest_helper.ps1" -Action Submit -Problem %2 -Language %3
if "%~1"=="help" powershell.exe -ExecutionPolicy Bypass -File "contest_helper.ps1" -Action Help

if "%~1"=="" (
    echo デフォルト: 状況確認
    powershell.exe -ExecutionPolicy Bypass -File "contest_helper.ps1" -Action Status
)
pause
"@
        $contestPath = Join-Path $NewDirPath "contest.bat"
        $contestBat | Out-File -FilePath $contestPath -Encoding ASCII
        Write-Host "   ✅ contest.bat を作成しました" -ForegroundColor Green
    }

    # 成功メッセージ
    Write-Host "`n" + ("=" * 50) -ForegroundColor Gray
    Write-Host "🎉 ABC$ContestNumber のフォルダ作成が完了しました！" -ForegroundColor Green
    Write-Host "📂 作成場所: $NewDirPath" -ForegroundColor Cyan
    Write-Host "📋 作成されたファイル:" -ForegroundColor Cyan
    foreach ($file in ($copiedFiles + "README.md")) {
        Write-Host "   - $file" -ForegroundColor White
    }

    # フォルダを開く
    if ($Open) {
        Write-Host "📁 エクスプローラーでフォルダを開いています..." -ForegroundColor Yellow
        Start-Process explorer.exe -ArgumentList $NewDirPath
    }

    # VS Codeでフォルダを開く
    if ($VSCode) {
        Write-Host "💻 VS Codeでフォルダを開いています..." -ForegroundColor Yellow
        Start-Process code -ArgumentList $NewDirPath
    }

    Write-Host "`n🚀 コンテスト頑張ってください！" -ForegroundColor Magenta

} catch {
    Write-Host "`n❌ エラーが発生しました: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}